# This is a basic workflow to help you get started with Actions

name: dev build CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  deployments: write
  packages: write
  issues: write
  pull-requests: write
  pages: write
  repository-projects: write
  actions: write
  checks: write
  discussions: write
  security-events: write
  statuses: write

jobs:
  test:
    strategy:
      matrix:
        python-versions: ['3.11']
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    outputs:
      package_version: ${{ steps.variables_step.outputs.package_version }}
      package_name: ${{ steps.variables_step.outputs.package_name }}
      repo_name: ${{ steps.variables_step.outputs.repo_name }}
      repo_owner: ${{ steps.variables_step.outputs.repo_owner }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions poetry

      - name: Declare variables for convenient use
        id: variables_step
        run: |
          echo "repo_owner=${GITHUB_REPOSITORY%/*}" >> $GITHUB_STATE
          echo "repo_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_STATE
          PACKAGE_NAME=$(poetry version | awk '{print $1}')
          echo "package_name=${PACKAGE_NAME}" >> $GITHUB_STATE
          PACKAGE_VERSION=$(poetry version --short)
          echo "package_version=${PACKAGE_VERSION}" >> $GITHUB_STATE
        shell: bash

      - name: test with tox
        run: tox

  publish_dev_build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry tox tox-gh-actions

      - name: Build wheels and source tarball
        run: |
          poetry version $(poetry version --short)-dev.$GITHUB_RUN_NUMBER
          poetry lock
          poetry build

      - name: publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            repository-url: https://test.pypi.org/legacy/
            skip-existing: true
